/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectConceptPanel.java
 *
 * Created on Aug 28, 2011, 9:49:21 PM
 */
package eu.opensme.cope.knowledgemanager.gui.classification.tree;

import java.awt.Component;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JTree;
import javax.swing.tree.DefaultTreeCellRenderer;

/**
 *
 * @author George
 */
public class SelectConceptPanel extends javax.swing.JPanel {

    private TreeDomainNodeData root;
    public CustomDomainTree jTree1;
    
    /** Creates new form SelectConceptPanel */
    public SelectConceptPanel(TreeDomainNodeData root) {
        this.root = root;
        initComponents();
        initMyComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initMyComponents() {
        
        jTree1 = new CustomDomainTree(root);
        jTree1.setAutoscrolls(true);
        jScrollPane1.setViewportView(jTree1);
        jTree1.setExpandsSelectedPaths(true);
        jTree1.setCellRenderer(new ConceptJTreeRenderer());
        jTree1.expandAll();
    }
    
    private class ConceptJTreeRenderer extends DefaultTreeCellRenderer {

        ImageIcon leafIcon, rootIcon;

        public ConceptJTreeRenderer() {
            this.leafIcon = new javax.swing.ImageIcon(getClass().getResource("/images/subclass.png"));
            this.rootIcon = new javax.swing.ImageIcon(getClass().getResource("/images/domains.png"));
        }

        @Override
        public Component getTreeCellRendererComponent(JTree tree, Object value, boolean selected, boolean expanded, boolean leaf, int row, boolean hasFocus) {
            super.getTreeCellRendererComponent(tree, value, selected, expanded, leaf, row, hasFocus);
            if (((TreeDomainNodeData) value).getName().equals("Concepts")) {
                setIcon(rootIcon);
                setIcon(rootIcon);
                setFont(new Font("Arial", Font.BOLD, 12));
            } else {
                setIcon(leafIcon);
                setIcon(leafIcon);
                setFont(new Font("Arial", Font.PLAIN, 12));
            }
            return this;
        }
    }
    
}
