//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.24 at 11:34:47 πμ EET 
//


package eu.opensme.cope.factgenerators.dependenciesgeneratorxmlschema;


import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the classcylejaxb.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: classcylejaxb.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClassycleClass }
     * 
     */
    public ClassycleClass createClass() {
        return new ClassycleClass();
    }

    /**
     * Create an instance of {@link Classes }
     * 
     */
    public Classes createClasses() {
        return new Classes();
    }

    /**
     * Create an instance of {@link Cycle }
     * 
     */
    public Cycle createCycle() {
        return new Cycle();
    }

    /**
     * Create an instance of {@link ClassRef }
     * 
     */
    public ClassRef createClassRef() {
        return new ClassRef();
    }

    /**
     * Create an instance of {@link CenterClasses }
     * 
     */
    public CenterClasses createCenterClasses() {
        return new CenterClasses();
    }

    /**
     * Create an instance of {@link BestFragmenters }
     * 
     */
    public BestFragmenters createBestFragmenters() {
        return new BestFragmenters();
    }

    /**
     * Create an instance of {@link PackageCycle }
     * 
     */
    public PackageCycle createPackageCycle() {
        return new PackageCycle();
    }

    /**
     * Create an instance of {@link PackageCycles }
     * 
     */
    public PackageCycles createPackageCycles() {
        return new PackageCycles();
    }

    /**
     * Create an instance of {@link ClassyclePackage }
     * 
     */
    public ClassyclePackage createPackage() {
        return new ClassyclePackage();
    }

    /**
     * Create an instance of {@link CenterPackages }
     * 
     */
    public CenterPackages createCenterPackages() {
        return new CenterPackages();
    }

    /**
     * Create an instance of {@link Cycles }
     * 
     */
    public Cycles createCycles() {
        return new Cycles();
    }

    /**
     * Create an instance of {@link PackageRef }
     * 
     */
    public PackageRef createPackageRef() {
        return new PackageRef();
    }

    /**
     * Create an instance of {@link Classycle }
     * 
     */
    public Classycle createClassycle() {
        return new Classycle();
    }

    /**
     * Create an instance of {@link ClassyclePackages }
     * 
     */
    public ClassyclePackages createPackages() {
        return new ClassyclePackages();
    }

}
