/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CoveragePanel.java
 *
 * Created on 6 Ιαν 2012, 10:43:30 πμ
 */
package eu.opensme.cope.componentvalidator.ui;

import eu.opensme.cope.componentvalidator.coverage.cfg.CfgMethod;
import eu.opensme.cope.componentvalidator.coverage.core.Coverage;
import java.util.Set;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thanasis
 */
public class CoveragePanel extends javax.swing.JPanel {

    private Coverage cover;
    
    /** Creates new form CoveragePanel */
    public CoveragePanel(double[] coverageMetrics, Coverage cover, Set<String> methodsList) {
        initComponents();

        this.cover = cover;
        DefaultTableModel model = (DefaultTableModel) coverageTable.getModel();
        for (Object[] object : cover.getInterfaceCoverageTable(methodsList)){
             model.addRow(object);
        }
        coverageTable.setModel(model);
        coverageTable.repaint();
        
        componentLcsajCoverage.setText(String.valueOf(coverageMetrics[0]) + "%");
        componentStmtCoverage.setText(String.valueOf(coverageMetrics[1]) + "%");
    }
    
    public CoveragePanel(double[] coverageMetrics, Coverage cover) {
        initComponents();

        this.cover = cover;
        DefaultTableModel model = (DefaultTableModel) coverageTable.getModel();
        for (Object[] object : cover.getCoverageTable()){
             model.addRow(object);
        }
        coverageTable.setModel(model);
        coverageTable.repaint();
        
        componentLcsajCoverage.setText(String.valueOf(coverageMetrics[0]) + "%");
        componentStmtCoverage.setText(String.valueOf(coverageMetrics[1]) + "%");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        coverageTable = new javax.swing.JTable();
        componentStmtCoverageLabel = new javax.swing.JLabel();
        componentStmtCoverage = new javax.swing.JLabel();
        componentLcasjCoverageLabel = new javax.swing.JLabel();
        componentLcsajCoverage = new javax.swing.JLabel();
        detailsButton = new javax.swing.JButton();

        coverageTable.setAutoCreateRowSorter(true);
        coverageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Method", "Lcsaj Cov. (%)", "Stmt Cov. (%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(coverageTable);

        componentStmtCoverageLabel.setFont(new java.awt.Font("Ubuntu", 1, 16));
        componentStmtCoverageLabel.setText("Statement Cov.: ");

        componentStmtCoverage.setFont(new java.awt.Font("Ubuntu", 1, 16));
        componentStmtCoverage.setForeground(new java.awt.Color(255, 0, 0));

        componentLcasjCoverageLabel.setFont(new java.awt.Font("Ubuntu", 1, 16));
        componentLcasjCoverageLabel.setText("Lcsaj Cov.: ");

        componentLcsajCoverage.setFont(new java.awt.Font("Ubuntu", 1, 16));
        componentLcsajCoverage.setForeground(new java.awt.Color(255, 0, 0));

        detailsButton.setText("Details");
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(detailsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(componentLcasjCoverageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(componentLcsajCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(componentStmtCoverageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(componentStmtCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(detailsButton)
                            .addComponent(componentLcasjCoverageLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(componentStmtCoverageLabel)
                            .addGap(4, 4, 4))
                        .addComponent(componentLcsajCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(componentStmtCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        if (coverageTable.getSelectedRow() != -1) {
            String selectedValue = coverageTable.getModel().getValueAt(coverageTable.convertRowIndexToModel(coverageTable.getSelectedRow()), 0).toString();
            CfgMethod selectedMethod = cover.getSelectedMethod(selectedValue);
            DetailsJDialog dialog = new DetailsJDialog(new JFrame(), "Methods Source Code", selectedMethod.getHtmlFileName());
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            JComponent newContentPane = new CoverageSourceViewer(selectedMethod);
            newContentPane.setOpaque(true);
            dialog.setContentPane(newContentPane);
            dialog.pack();
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_detailsButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel componentLcasjCoverageLabel;
    private javax.swing.JLabel componentLcsajCoverage;
    private javax.swing.JLabel componentStmtCoverage;
    private javax.swing.JLabel componentStmtCoverageLabel;
    private javax.swing.JTable coverageTable;
    private javax.swing.JButton detailsButton;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
