package eu.opensme.cope.recommenders.entities;
// Generated Apr 24, 2012 1:14:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DependenciesTypeId generated by hbm2java
 */
@Embeddable
public class DependenciesTypeId  implements java.io.Serializable {


     private long dependee;
     private long dependency;
     private String depencencyType;
     private String depencencySubType;

    public DependenciesTypeId() {
    }

    public DependenciesTypeId(long dependee, long dependency, String depencencyType, String depencencySubType) {
       this.dependee = dependee;
       this.dependency = dependency;
       this.depencencyType = depencencyType;
       this.depencencySubType = depencencySubType;
    }
   

    @Column(name="dependee", nullable=false)
    public long getDependee() {
        return this.dependee;
    }
    
    public void setDependee(long dependee) {
        this.dependee = dependee;
    }

    @Column(name="dependency", nullable=false)
    public long getDependency() {
        return this.dependency;
    }
    
    public void setDependency(long dependency) {
        this.dependency = dependency;
    }

    @Column(name="depencencyType", nullable=false, length=40)
    public String getDepencencyType() {
        return this.depencencyType;
    }
    
    public void setDepencencyType(String depencencyType) {
        this.depencencyType = depencencyType;
    }

    @Column(name="depencencySubType", nullable=false, length=40)
    public String getDepencencySubType() {
        return this.depencencySubType;
    }
    
    public void setDepencencySubType(String depencencySubType) {
        this.depencencySubType = depencencySubType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DependenciesTypeId) ) return false;
		 DependenciesTypeId castOther = ( DependenciesTypeId ) other; 
         
		 return (this.getDependee()==castOther.getDependee())
 && (this.getDependency()==castOther.getDependency())
 && ( (this.getDepencencyType()==castOther.getDepencencyType()) || ( this.getDepencencyType()!=null && castOther.getDepencencyType()!=null && this.getDepencencyType().equals(castOther.getDepencencyType()) ) )
 && ( (this.getDepencencySubType()==castOther.getDepencencySubType()) || ( this.getDepencencySubType()!=null && castOther.getDepencencySubType()!=null && this.getDepencencySubType().equals(castOther.getDepencencySubType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getDependee();
         result = 37 * result + (int) this.getDependency();
         result = 37 * result + ( getDepencencyType() == null ? 0 : this.getDepencencyType().hashCode() );
         result = 37 * result + ( getDepencencySubType() == null ? 0 : this.getDepencencySubType().hashCode() );
         return result;
   }   


}


