/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompareComponentClassesDialog.java
 *
 * Created on 7 Δεκ 2011, 2:56:39 μμ
 */
package eu.opensme.cope.ui;

import eu.opensme.cope.recommenders.entities.ClassAnalysis;
import eu.opensme.cope.recommenders.entities.ClassAnalysisNameComparator;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author akritiko
 */
public class CompareComponentClassesDialog extends javax.swing.JPanel {

    /** Creates new form CompareComponentClassesDialog */
    public CompareComponentClassesDialog(List<ClassAnalysis> selectedComponentClasses, List<ClassAnalysis> wannabeComponentClasses) {
        initComponents();
        
        Collections.sort(selectedComponentClasses, new ClassAnalysisNameComparator());
        Collections.sort(wannabeComponentClasses, new ClassAnalysisNameComparator());
       

        DefaultListModel model1 = new DefaultListModel();
        jList1.setModel(model1);
        for (int i = 0; i < selectedComponentClasses.size(); i++) {
            model1.add(i, selectedComponentClasses.get(i).getName());
        }

        DefaultListModel model2 = new DefaultListModel();
        jList2.setModel(model2);
        for (int i = 0; i < wannabeComponentClasses.size(); i++) {
            model2.add(i, wannabeComponentClasses.get(i).getName());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(280);

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pivot Component"));
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jList2.setBorder(javax.swing.BorderFactory.createTitledBorder("Candidate Component"));
        jScrollPane2.setViewportView(jList2);

        jSplitPane1.setRightComponent(jScrollPane2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
