/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenReuseProjectDialog.java
 *
 * Created on 10 Ιουν 2011, 11:35:29 πμ
 */
package eu.opensme.cope.ui;

import eu.opensme.cope.domain.ReuseProject;
import java.io.File;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.hibernate.transaction.JOTMTransactionManagerLookup;

/**
 *
 * @author george
 */
public class HistoryAnalysisDialog extends javax.swing.JDialog {

    private ReuseProject project;
    private ComponentAdaptationEnvironmentMain parent;
    //private List<Project> projects;

    /** Creates new form OpenReuseProjectDialog */
    public HistoryAnalysisDialog(java.awt.Frame parent, boolean modal, ReuseProject reuseProject, ComponentAdaptationEnvironmentMain caem) {
        super(parent, modal);
        initComponents();

        this.project = reuseProject;
        this.parent = caem;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        openReuseProjectButton = new javax.swing.JButton();
        cancelOpenReuseProjectButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        fileChooserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Select CVS history file (.xml format)  ");

        openReuseProjectButton.setText("START");
        openReuseProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openReuseProjectButtonActionPerformed(evt);
            }
        });

        cancelOpenReuseProjectButton.setText("Cancel");
        cancelOpenReuseProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOpenReuseProjectButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Specify the root package");

        fileChooserButton.setText("Choose");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(167, 167, 167))
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(openReuseProjectButton)
                        .addGap(15, 15, 15)
                        .addComponent(cancelOpenReuseProjectButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileChooserButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileChooserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openReuseProjectButton)
                    .addComponent(cancelOpenReuseProjectButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelOpenReuseProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOpenReuseProjectButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelOpenReuseProjectButtonActionPerformed

    private void openReuseProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openReuseProjectButtonActionPerformed
        if ( (this.project != null) && (this.parent != null) && (!jTextField1.getText().equals("")) && (!jTextField2.getText().equals("")) ) {
            JDialog dialog = new JDialog(this, "History Analysis");
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            JComponent newContentPane = new GenerateHistoryProgressPanel(this.project, this.parent, jTextField1.getText(), jTextField2.getText());
            newContentPane.setOpaque(true);
            dialog.setContentPane(newContentPane);
            dialog.pack();
            this.setVisible(false);
            dialog.setVisible(true);
            this.repaint();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please fill all the appropriate information", "Unsufficient Input", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_openReuseProjectButtonActionPerformed

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        JFileChooser newReuseProjectJarFileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("XML file", "xml");
        newReuseProjectJarFileChooser.addChoosableFileFilter(filter);
        int returnValue = newReuseProjectJarFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = newReuseProjectJarFileChooser.getSelectedFile();
            jTextField1.setText(file.getAbsolutePath());
        }
}//GEN-LAST:event_fileChooserButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelOpenReuseProjectButton;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton openReuseProjectButton;
    // End of variables declaration//GEN-END:variables
}
