/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewReuseProjectDialog.java
 *
 * Created on 4 Ιουν 2011, 9:31:09 μμ
 */
package eu.opensme.cope.ui;

import eu.opensme.cope.domain.ReuseProject;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.filechooser.FileFilter;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.hibernate.HibernateException;

/**
 *
 * @author george
 */
public class NewReuseProjectDialog extends javax.swing.JDialog {

    private ReuseProject project;
    private String lastDirectory;

    /** Creates new form NewReuseProjectDialog */
    public NewReuseProjectDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lastDirectory = "";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reuseProjectNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jarFilenameTextField = new javax.swing.JTextField();
        fileChooserButton = new javax.swing.JButton();
        createNewReuseProjectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        creationProblemLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dependenciesList = new javax.swing.JList();
        addDependencyButton = new javax.swing.JButton();
        removeDependencyButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        repoURLTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        srcDirTextField = new javax.swing.JTextField();
        srcDirChooseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Reuse Project Properties");

        jLabel1.setText("Reuse Project Name:");

        jLabel2.setText("JAR File:");

        fileChooserButton.setText("Choose");
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        createNewReuseProjectButton.setText("Create Reuse Project");
        createNewReuseProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewReuseProjectButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        creationProblemLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        creationProblemLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setText("Dependencies:");

        dependenciesList.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(dependenciesList);

        addDependencyButton.setText("Add");
        addDependencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDependencyButtonActionPerformed(evt);
            }
        });

        removeDependencyButton.setText("Remove");
        removeDependencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDependencyButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Repository URL:");

        jLabel5.setText("Source Code Directory:");

        srcDirChooseButton.setText("Choose");
        srcDirChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srcDirChooseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(creationProblemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createNewReuseProjectButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                                .addComponent(cancelButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reuseProjectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                    .addComponent(jarFilenameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                    .addComponent(repoURLTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                                    .addComponent(srcDirTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(srcDirChooseButton)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(removeDependencyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addDependencyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fileChooserButton)))))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(reuseProjectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jarFilenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileChooserButton)
                        .addGap(18, 18, 18)
                        .addComponent(addDependencyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeDependencyButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(repoURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(srcDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(srcDirChooseButton))
                .addGap(21, 21, 21)
                .addComponent(creationProblemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createNewReuseProjectButton))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        JFileChooser newReuseProjectJarFileChooser = new JFileChooser();
        newReuseProjectJarFileChooser.setCurrentDirectory(new File(lastDirectory));
        FileFilter filter = new FileNameExtensionFilter("JAR file", "jar");
        newReuseProjectJarFileChooser.addChoosableFileFilter(filter);
        int returnValue = newReuseProjectJarFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = newReuseProjectJarFileChooser.getSelectedFile();
            lastDirectory = file.getParent();
            jarFilenameTextField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    private void createNewReuseProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewReuseProjectButtonActionPerformed
        creationProblemLabel.setText("");
        String projectName = reuseProjectNameTextField.getText();
        if ("".equals(projectName) || projectName == null) {
            creationProblemLabel.setText("You must provide a project name");
            return;
        }
        String projectLocation = ReuseProject.getReuseProjectsLocation() + projectName;

        String projectJARFilename = jarFilenameTextField.getText();
        if ("".equals(projectJARFilename) || projectJARFilename == null) {
            creationProblemLabel.setText("You must provide a project jar file");
            return;
        }

        List<String> dependenciesJARs = new ArrayList<String>();
        int listSize = dependenciesList.getModel().getSize();
        for (int i=0; i<listSize; i++) {
            String s = (String) dependenciesList.getModel().getElementAt(i);
            dependenciesJARs.add(s);
        }

        String repoURL = repoURLTextField.getText();

        String srcDir = srcDirTextField.getText();
        if ("".equals(srcDir) || srcDir == null) {
            creationProblemLabel.setText("You must provide a source code directory");
            return;
        }

        ReuseProject reuseProject = new ReuseProject(projectLocation, 
                projectName,
                projectJARFilename,
                repoURL,
                dependenciesJARs,
                srcDir);

        try {
            boolean success = reuseProject.createReuseProject();
            if (!success) {
                creationProblemLabel.setText("Project directory already exists. Please choose another.");
                return;
            }
        } catch (IOException ioe) {
            creationProblemLabel.setText(ioe.getMessage());
            return;
        } catch (HibernateException he) {
            creationProblemLabel.setText(he.getMessage());
            return;
        }
        this.project = reuseProject;
        this.setVisible(false);
    }//GEN-LAST:event_createNewReuseProjectButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addDependencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDependencyButtonActionPerformed
        JFileChooser newReuseProjectJarFileChooser = new JFileChooser();
        newReuseProjectJarFileChooser.setCurrentDirectory(new File(lastDirectory));
        FileFilter filter = new FileNameExtensionFilter("JAR file", "jar");
        newReuseProjectJarFileChooser.addChoosableFileFilter(filter);
        newReuseProjectJarFileChooser.setMultiSelectionEnabled(true);
        int returnValue = newReuseProjectJarFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File[] files = newReuseProjectJarFileChooser.getSelectedFiles();
            DefaultListModel model = (DefaultListModel) dependenciesList.getModel();
            for (File file : files) {
                model.addElement(file.getAbsolutePath());
                if(!lastDirectory.equals(file.getParent())){
                    lastDirectory = file.getParent();
                }
            }
        }
    }//GEN-LAST:event_addDependencyButtonActionPerformed

    private void removeDependencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDependencyButtonActionPerformed
        DefaultListModel model = (DefaultListModel) dependenciesList.getModel();
        int[] selectedIndices = dependenciesList.getSelectedIndices();
        for (int i = selectedIndices.length-1; i>=0; i--) {
            model.remove(i);
        }
    }//GEN-LAST:event_removeDependencyButtonActionPerformed

    private void srcDirChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srcDirChooseButtonActionPerformed
        JFileChooser srcDirFileChooser = new JFileChooser();
        srcDirFileChooser.setCurrentDirectory(new File(lastDirectory));
        srcDirFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        srcDirFileChooser.setMultiSelectionEnabled(false);
        int returnValue = srcDirFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = srcDirFileChooser.getSelectedFile();
            lastDirectory = file.getAbsolutePath();
            srcDirTextField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_srcDirChooseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                NewReuseProjectDialog dialog = new NewReuseProjectDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public ReuseProject getProject() {
        return project;
    }

    public void setProject(ReuseProject project) {
        this.project = project;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDependencyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createNewReuseProjectButton;
    private javax.swing.JLabel creationProblemLabel;
    private javax.swing.JList dependenciesList;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jarFilenameTextField;
    private javax.swing.JButton removeDependencyButton;
    private javax.swing.JTextField repoURLTextField;
    private javax.swing.JTextField reuseProjectNameTextField;
    private javax.swing.JButton srcDirChooseButton;
    private javax.swing.JTextField srcDirTextField;
    // End of variables declaration//GEN-END:variables
}
