/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenReuseProjectDialog.java
 *
 * Created on 10 Ιουν 2011, 11:35:29 πμ
 */
package eu.opensme.cope.ui;

import eu.opensme.cope.recommenders.entities.Project;
import eu.opensme.cope.util.HibernateUtil;
import eu.opensme.cope.domain.ReuseProject;
import java.util.List;
import javax.swing.DefaultListModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;


/**
 *
 * @author george
 */
public class OpenReuseProjectDialog extends javax.swing.JDialog {

    private ReuseProject project;
    //private List<Project> projects;

    /** Creates new form OpenReuseProjectDialog */
    public OpenReuseProjectDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DefaultListModel m = (DefaultListModel) availableReuseProjectsList.getModel();
        //perform a hibernate query to populate list
        try {
            String query = "select from Project";
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            //get the given project's id
            Query q = session.createQuery(query);
            List<Project> projects = q.list();
            int i=0;
            for (Project p : projects) {
                m.add(i++, p);
            }
        } catch (HibernateException he) {
            openReuseProjectErrorMessageLabel.setText(he.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableReuseProjectsList = new javax.swing.JList();
        openReuseProjectButton = new javax.swing.JButton();
        cancelOpenReuseProjectButton = new javax.swing.JButton();
        openReuseProjectErrorMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Select Project");

        availableReuseProjectsList.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(availableReuseProjectsList);

        openReuseProjectButton.setText("Open");
        openReuseProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openReuseProjectButtonActionPerformed(evt);
            }
        });

        cancelOpenReuseProjectButton.setText("Cancel");
        cancelOpenReuseProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOpenReuseProjectButtonActionPerformed(evt);
            }
        });

        openReuseProjectErrorMessageLabel.setFont(new java.awt.Font("Tahoma", 2, 12));
        openReuseProjectErrorMessageLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(openReuseProjectButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(cancelOpenReuseProjectButton)))
                    .addComponent(openReuseProjectErrorMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(openReuseProjectErrorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openReuseProjectButton)
                    .addComponent(cancelOpenReuseProjectButton))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelOpenReuseProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOpenReuseProjectButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelOpenReuseProjectButtonActionPerformed

    private void openReuseProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openReuseProjectButtonActionPerformed
        Project p = (Project) availableReuseProjectsList.getSelectedValue();
        project = ReuseProject.openReuseProject(p);
        this.setVisible(false);
    }//GEN-LAST:event_openReuseProjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                OpenReuseProjectDialog dialog = new OpenReuseProjectDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public ReuseProject getProject() {
        return project;
    }

    public void setProject(ReuseProject project) {
        this.project = project;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList availableReuseProjectsList;
    private javax.swing.JButton cancelOpenReuseProjectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openReuseProjectButton;
    private javax.swing.JLabel openReuseProjectErrorMessageLabel;
    // End of variables declaration//GEN-END:variables
}
