/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReuseProjectBrowserPanel.java
 *
 * Created on 11 Ιουν 2011, 10:27:57 πμ
 */
package eu.opensme.cope.ui;

import eu.opensme.cope.domain.ReuseProject;
import eu.opensme.cope.factgenerators.DocumentationGenerator;
import eu.opensme.cope.recommenders.entities.ClassAnalysis;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.RowSorterEvent;
import javax.swing.event.RowSorterListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.tree.DefaultMutableTreeNode;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;

/**
 *
 * @author george
 */
public class ReuseProjectBrowserPanel extends javax.swing.JPanel {

    private ReuseProject reuseProject;
    private DefaultMutableTreeNode master;
    private File currentSelection;
    private ClassAnalysis selectedClass;

    /** Creates new form ReuseProjectBrowserPanel */
    public ReuseProjectBrowserPanel(ReuseProject reuseProject) {
        this.reuseProject = reuseProject;
        master = new DefaultMutableTreeNode(reuseProject.getProject().getProjecttitle());
        listAllFiles(new File(reuseProject.getSrcDir()), master, Boolean.TRUE);
        currentSelection = null;
        initComponents();
        classMetricsTable.getRowSorter().addRowSorterListener(new RowSorterListener() {

            public void sorterChanged(RowSorterEvent rse) {
                TableCellRenderer renderer = new CustomTableCellRenderer(0);
                classMetricsTable.setDefaultRenderer(Object.class, renderer);
                classMetricsTable.validate();
                repaint();
            }
        });
    }

    /** Creates new form ReuseProjectBrowserPanel where
     *  search results appear first
     */
    public void visualizeSearchResults(Vector<ClassAnalysis> searchResults) {
        if (this.reuseProject == null) {
            return;
        }
        ClassMetricsTableModel model = new ClassMetricsTableModel(reuseProject.getProject());
        int counter = 0;
        for (int i = 0; i < searchResults.size(); i++) {
            int place = model.getPlace(searchResults.elementAt(i));
            if (place < 0) {
                continue;
            }
            ClassAnalysis temp = model.getRowObject(place);
            model.setValue(counter, searchResults.elementAt(i));
            model.setValue(place, temp);
            counter++;
        }
        classMetricsTable.setModel(model);
        this.initColumnSizes(classMetricsTable);
        classMetricsTable.getRowSorter().addRowSorterListener(new RowSorterListener() {

            public void sorterChanged(RowSorterEvent rse) {
                TableCellRenderer renderer = new CustomTableCellRenderer(0);
                classMetricsTable.setDefaultRenderer(Object.class, renderer);
                classMetricsTable.validate();
                repaint();
            }
        });
        TableCellRenderer renderer = new CustomTableCellRenderer(counter);
        classMetricsTable.setDefaultRenderer(Object.class, renderer);
        classMetricsTable.validate();
        this.repaint();
    }

    public void resetSearchResults() {
        TableCellRenderer renderer = new CustomTableCellRenderer(0);
        classMetricsTable.setDefaultRenderer(Object.class, renderer);
        classMetricsTable.validate();
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        viewSourceMenuItem = new javax.swing.JMenuItem();
        extractComponentMenuItem = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        srcDirTree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        classMetricsTable = new javax.swing.JTable();

        viewSourceMenuItem.setText("View Source Code...");
        viewSourceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSourceMenuItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(viewSourceMenuItem);

        extractComponentMenuItem.setText("Extract component from here...");
        extractComponentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractComponentMenuItemActionPerformed(evt);
            }
        });
        jPopupMenu1.add(extractComponentMenuItem);

        srcDirTree.setModel(new javax.swing.tree.DefaultTreeModel(master));
        srcDirTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                srcDirTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(srcDirTree);

        jSplitPane1.setLeftComponent(jScrollPane1);

        classMetricsTable.setAutoCreateRowSorter(true);
        classMetricsTable.setModel(new ClassMetricsTableModel(reuseProject.getProject()));
        classMetricsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        classMetricsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classMetricsTableMouseClicked(evt);
            }
        });
        initColumnSizes(classMetricsTable);
        jScrollPane2.setViewportView(classMetricsTable);

        jSplitPane1.setRightComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void srcDirTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_srcDirTreeValueChanged
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) evt.getPath().getLastPathComponent();
        if ((node == null) || (node.isRoot())) {
            //Nothing is selected
            return;
        }
        FileInfo selection = (FileInfo) node.getUserObject();
        currentSelection = selection.getFile();
        showDocForFile(currentSelection);
        //refreshReuseProjectBrowserTabbedPane();
    }

    private void showDocForFile(File fileSysEntity) {
        if (fileSysEntity == null) {
            return;
        }
        File f = DocumentationGenerator.getDocForFile(
                reuseProject.getProjectLocation(),
                reuseProject.getSrcDir(),
                fileSysEntity.getAbsolutePath(),
                fileSysEntity.isDirectory());

        if (f == null) {
            return;
        }
        /*
        docPanel.removeAll();
        String filename = "file://" + f.getAbsolutePath();
        JPanel webBrowserPanel = new JPanel(new BorderLayout());
        webBrowserPanel.setOpaque(false);
        JWebBrowser browser = new JWebBrowser();
        browser.navigate(filename);
        webBrowserPanel.add(browser, BorderLayout.CENTER);
        docPanel.add(webBrowserPanel, BorderLayout.CENTER);
         * 
         */
        String filename = "file://" + f.getAbsolutePath();
        JDialog docDialog = new JDialog((JFrame) getTopLevelAncestor(),
                "Documentation for file " + filename, true);
        docDialog.setSize(800, 800);
        docDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        JPanel webBrowserPanel = new JPanel(new BorderLayout());
        try {
            JEditorPane browser = new JEditorPane(filename);
            browser.setEditable(false);
            final JScrollPane scrollPane = new JScrollPane(browser,
                    JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                    JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            scrollPane.getVerticalScrollBar().setUnitIncrement(16);
            scrollPane.getVerticalScrollBar().addAdjustmentListener(new AdjustmentListener() {
                @Override
                public void adjustmentValueChanged(AdjustmentEvent e) {
                    e.getValueIsAdjusting();
                }
            });
            scrollPane.getVerticalScrollBar().setValue(0);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
            webBrowserPanel.add(scrollPane, BorderLayout.CENTER);
            docDialog.setContentPane(webBrowserPanel);
            //docDialog.pack();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        docDialog.setVisible(true);
    }

    private void refreshMetricsScrollPaneContents(File fileSysEntity) {
        if (fileSysEntity == null) {
            //metricsLabel.setText("No element is currently selected");
            return;
        }
        //metricsLabel.setText("Metrics will be displayed here for " + fileSysEntity.getAbsolutePath() + " currently selected");
    }//GEN-LAST:event_srcDirTreeValueChanged

    private void classMetricsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classMetricsTableMouseClicked
        int selectedRow = this.classMetricsTable.getSelectedRow();
        if (selectedRow >= 0) {
            selectedRow = this.classMetricsTable.convertRowIndexToModel(selectedRow);
            ClassMetricsTableModel model = (ClassMetricsTableModel) this.classMetricsTable.getModel();
            selectedClass = model.getRowObject(selectedRow);
            if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {

                System.out.println("Class " + selectedClass.getName() + " was selected.");
            } else {
                jPopupMenu1.show(this, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_classMetricsTableMouseClicked

    private void extractComponentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractComponentMenuItemActionPerformed
        if (selectedClass != null) {
//            System.out.println("Extracting component for class " + selectedClass.getName());
//            String destFolder = ReuseProject.getReuseProjectsLocation()
//                    + selectedClass.getName() + "Component";
//            int i = selectedClass.extractComponent(reuseProject.getSrcDir(), destFolder).size();
//            JOptionPane.showMessageDialog(
//                    this,
//                    "Component extraction finished. " + i + " classes were extracted to folder " + destFolder);
            JDialog dialog = new JDialog((ComponentAdaptationEnvironmentMain) this.getParent().getParent().getParent().getParent().getParent(), "Dependency Maker");
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            DependencyMakerPanel newContentPane = new DependencyMakerPanel(reuseProject, reuseProject.getProject().getClasses());

            newContentPane.setOpaque(true);
            dialog.setContentPane(newContentPane);
            dialog.setVisible(true);
            dialog.pack();
            newContentPane.setSelectedClass(selectedClass);
        }
    }//GEN-LAST:event_extractComponentMenuItemActionPerformed

    private void viewSourceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSourceMenuItemActionPerformed
        if (selectedClass != null) {
            String text = null;
            String filePath = this.reuseProject.getSrcDir()+ File.separator + selectedClass.getName().replace('.', File.separatorChar) + ".java";
            File javaFile = new File(filePath);
            JDialog sourceDialog = new JDialog();
            JPanel cp = new JPanel(new BorderLayout());
            try {
                text = getSourceForFile(javaFile);
            } catch (FileNotFoundException ex) {
                cp.add(new JLabel("File not found: " + filePath));
                sourceDialog.setContentPane(cp);
                sourceDialog.setEnabled(true);
                sourceDialog.pack();
                return;
            }
            RSyntaxTextArea textArea = new RSyntaxTextArea();
            textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
            textArea.setCodeFoldingEnabled(true);
            textArea.setAntiAliasingEnabled(true);
            textArea.setEditable(false);
            
            textArea.setText(text);
            RTextScrollPane sp = new RTextScrollPane(textArea);
            sp.setFoldIndicatorEnabled(true);
            cp.add(sp);

            sourceDialog.setContentPane(cp);
            sourceDialog.setTitle(javaFile.getName() + " (" + selectedClass.getName() +")");
            sourceDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            sourceDialog.setVisible(true);
            sourceDialog.pack();
            sourceDialog.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_viewSourceMenuItemActionPerformed

    private String getSourceForFile(File javaFile) throws FileNotFoundException {
        StringBuilder text = new StringBuilder();
        String NL = System.getProperty("line.separator");
        Scanner scanner = new Scanner(new FileInputStream(javaFile));
        try {
            while (scanner.hasNextLine()) {
                text.append(scanner.nextLine() + NL);
            }
        } finally {
            scanner.close();
        }
        return text.toString();
    }

    public final void listAllFiles(File directory, DefaultMutableTreeNode parent, Boolean recursive) {
        File[] children = directory.listFiles(); // list all the files in the directory
        for (File child : children) { // loop through each
            DefaultMutableTreeNode node = new DefaultMutableTreeNode(new FileInfo(child));
            // only display the node if it isn't a folder, and if this is a recursive call
            if (child.isDirectory() && recursive) {
                parent.add(node); // add as a child node
                listAllFiles(child, node, recursive); // call again for the subdirectory
            } else if (!child.isDirectory()) { // otherwise, if it isn't a directory
                parent.add(node); // add it as a node and do nothing else
            }
        }
    }

    private void initColumnSizes(javax.swing.JTable table) {
        ClassMetricsTableModel model = (ClassMetricsTableModel) table.getModel();
        javax.swing.table.TableColumn column = null;
        Component comp = null;
        int headerWidth = 0;
        int cellWidth = 0;
        Object[] exampleValues = model.exampleValues();
        javax.swing.table.TableCellRenderer headerRenderer =
                table.getTableHeader().getDefaultRenderer();
        int columnCount = model.getColumnCount();
        for (int i = 0; i < columnCount; i++) {
            column = table.getColumnModel().getColumn(i);

            comp = headerRenderer.getTableCellRendererComponent(
                    null, column.getHeaderValue(),
                    false, false, 0, 0);
            headerWidth = comp.getPreferredSize().width;

            comp = table.getDefaultRenderer(model.getColumnClass(i)).
                    getTableCellRendererComponent(
                    table, exampleValues[i],
                    false, false, 0, i);
            cellWidth = comp.getPreferredSize().width;


            System.out.println("Initializing width of column "
                    + i + ". "
                    + "headerWidth = " + headerWidth
                    + "; cellWidth = " + cellWidth);


            column.setPreferredWidth(Math.max(headerWidth, cellWidth));
        }
    }

    private class CustomTableCellRenderer extends DefaultTableCellRenderer {

        int threshold = 0;

        public CustomTableCellRenderer(int threshold) {
            this.threshold = threshold;
        }

        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if (row < threshold) {
                cell.setBackground(Color.pink);
            } else {
                cell.setBackground(new Color(242, 241, 240));
            }

            return cell;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable classMetricsTable;
    private javax.swing.JMenuItem extractComponentMenuItem;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree srcDirTree;
    private javax.swing.JMenuItem viewSourceMenuItem;
    // End of variables declaration//GEN-END:variables
}
